### ISSUE TITLE
No prediction

### ISSUE THREAD

**Issue by Zumbalamambo** [matterport/Mask_RCNN#401] opened 2018-04-05 17:39 UTC
I have annotated hundreds of images and have trained for 30 epoch . However when I try to predict after the training, it is not segmenting the object...How can I be able to sort this out?

**Comment by waleedka** [comment] 2018-04-05 22:44
Duplicate of https://github.com/matterport/Mask_RCNN/issues/396

**Closed by waleedka** 2018-04-05 22:44 UTC
