### ISSUE TITLE
Serving fails since pyfunc isn't supported in serving environment.

### ISSUE THREAD

**Issue by rays2pix** [matterport/Mask_RCNN#99] opened 2017-11-27 05:50 UTC
Hi,
I get the below error when I start tensorflow_model_server. 
"Op type not registered 'PyFunc'"
And the only suggestion I get around web is to reimplement pyfunc as tensorflow operations. Do you know of any other ways?

**Comment by waleedka** [comment] 2017-11-27 07:52
I didn't know that Python layers are not supported on TensorFlow serving. That's a big limitation of the serving solution. 

The only place py_func is used is in the DetectionLayer. I was planning to convert it to TensorFlow operations but didn't get time to work on it, no other reason. It shouldn't be too hard to convert if you want to try that. 

Alternatively, you can skip TensorFlow serving and run the detection code just like any other Python script. It might add a bit of overhead, but unless you're serving a ton of requests I think it shouldn't be too bad.

**Comment by rays2pix** [comment] 2017-11-27 09:51
Oh okay, Thank you for the quick response.

**Comment by Cpruce** [comment] 2017-12-31 17:24
Hi @waleedka,

I'd like to contribute this to the repo. I have already started the conversion to tf functions and am debugging now. I've pinged you my work on model.py.

**Comment by Cpruce** [comment] 2017-12-31 23:41
Awesome, thanks Waleed!

**Comment by Cpruce** [comment] 2018-02-12 21:14
Thanks again @waleedka and just reminding here to close the issue since the problem is now resolved!

**Closed** 2018-02-13 09:02 UTC

**Comment by slothkong** [comment] 2018-10-04 15:36
@rays2pix , @Cpruce may I ask if you were able to mount the model on TFserving using a default `ModelServer`? I'm still looking at the docs but I get the feeling the default 'predic.proto' message is not suitable to serve models with several output heads. Any tips?

**Comment by dcyoung** [comment] 2018-10-04 16:47
Here is a snippet from my serving export script. You simply assign multiple outputs. 
```python
       detection_signature = (
            build_signature_def(
                inputs={
                    "flattened_image_tensor": build_tensor_info(serving_inputs['raw_image']),
                    "input_image_meta": build_tensor_info(serving_inputs['raw_image_meta'])
                },
                outputs={
                    'detection': build_tensor_info(model_outputs[0]),
                    'mask': build_tensor_info(model_outputs[1])
                },
                method_name=signature_constants.PREDICT_METHOD_NAME
            )
        )
`

**Comment by slothkong** [comment] 2018-10-10 21:05
@dcyoung may I ask where did you learn about this???

**Comment by dcyoung** [comment] 2018-10-11 01:48
Good old trial and error :smile:

**Comment by alexeygrigorev** [comment] 2018-10-11 11:35
@dcyoung could you please share the full script for exporting the model to tf-serving? if you also have some code for talking to this tf-serving service, this would be great as well
