### ISSUE TITLE
 module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'

### ISSUE THREAD

**Issue by farzadzare** [matterport/Mask_RCNN#694] opened 2018-06-18 11:07 UTC
hi everybody 
I want to use Mask-RCNN demo.py in my jupyter notebook but when i ran the the demo code in part of Create Model and Load Trained Weights i faced with such problem

AttributeError                            Traceback (most recent call last)
<ipython-input-6-138183a2a830> in <module>()
      3 
      4 # Load weights trained on MS-COCO
----> 5 model.load_weights(COCO_MODEL_PATH, by_name=True)

~/Downloads/Mask_RCNN/mrcnn/model.py in load_weights(self, filepath, by_name, exclude)
   2117 
   2118         if by_name:
-> 2119             topology.load_weights_from_hdf5_group_by_name(f, layers)
   2120         else:
   2121             topology.load_weights_from_hdf5_group(f, layers)

AttributeError: module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'

please help me

**Comment by JulienDufour** [comment] 2018-06-18 12:28
Hi,

Try to re install Keras 2.1.6 instead of the last version (i.e., 2.2.0).

pip install 'keras==2.1.6' --force--reinstall

**Comment by engineer1109** [comment] 2018-06-18 14:56
@JulienDufour @farzadzare A better solution
You need to clean your build dir first.
Then mrcnn/model.py, replace the "topology" with "saving".
Then run python3 setup.py install

**Comment by hadim** [comment] 2018-06-18 15:05
Same error here.

**Comment by engineer1109** [comment] 2018-06-18 15:06
@hadim Look my comments. I have given the solution.

**Comment by JulienDufour** [comment] 2018-06-18 16:04
@engineer1109

**Comment by JulienDufour** [comment] 2018-06-18 16:07
Thanks @engineer1109 , I didn't take time to search the new location. Also in saving : 

>>> from keras.engine import saving
>>> saving.load_
saving.load_attributes_from_hdf5_group(
saving.load_model(
saving.load_weights_from_hdf5_group(
saving.load_weights_from_hdf5_group_by_name(

**Comment by csq20081052** [comment] 2018-06-20 15:35
@engineer1109 can you describe in detail，do you mean replace the 'topology' with 'saving' in model.py??

**Comment by engrchrishenry** [comment] 2018-06-20 17:05
@hadim @csq20081052  You can follow this pull request #662  to solve your problem. You just need to change 'topology' with 'saving' in model.py as shown in the referenced pull request.

**Comment by csq20081052** [comment] 2018-06-26 01:08
@engrchrishenry thx, I haved solved this problem.

**Comment by roobooot** [comment] 2018-06-27 16:21
https://github.com/matterport/Mask_RCNN/pull/662/files
to do like above, and run `python setup.py install`
then it would run

**Comment by farzadzare** [comment] 2018-06-27 16:45
Thanks @engineer1109,  Your suggestion is awesome

**Comment by farzadzare** [comment] 2018-06-27 16:48
Thanks @roobooot

**Comment by waleedka** [comment] 2018-07-12 00:02
Fixed in https://github.com/matterport/Mask_RCNN/pull/662

**Closed by waleedka** 2018-07-12 00:02 UTC

**Comment by azhouqian** [comment] 2018-11-11 06:53
Hi, I want to know the meaning of "You need to clean your build dir first.". I try to solve the problem by replacing "toppology"by "saving", but it has the same problem as before. I think the problem is I haven't do it correctly with "You need to clean your build dir first."

**Comment by azhouqian** [comment] 2018-11-11 06:53
Hi, I want to know the meaning of "You need to clean your build dir first.". I try to solve the problem by replacing "toppology"by "saving", but it has the same problem as before. I think the problem is I haven't do it correctly with "You need to clean your build dir first." @engineer1109

**Comment by banafsh89** [comment] 2019-03-08 09:55
It doesn't work for me! After I do the changes that mentioned, I get the error "name saving is not defined". Do you have any idea?

**Comment by olivier-gillet** [comment] 2019-07-24 09:05
@JulienDufour What version of tensorflow are you using with keras 2.1.6 ?

**Comment by ShaguftaMethwani** [comment] 2019-09-21 17:32
For m it still gives the same error of module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'   even after replacin wih saving. How is hat happening?

**Comment by pranjalsharma26** [comment] 2020-02-06 20:33
> @JulienDufour @farzadzare A better solution
> You need to clean your build dir first.
> Then mrcnn/model.py, replace the "topology" with "saving".
> Then run python3 setup.py install

Yaa it works for me too. Thanks a lot.

**Comment by anmspro** [comment] 2020-06-22 16:18
> For m it still gives the same error of module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name' even after replacin wih saving. How is hat happening?

same problem.. following

**Comment by Meoooww** [comment] 2022-03-01 17:34
> Hi, I want to know the meaning of "You need to clean your build dir first.". I try to solve the problem by replacing "toppology"by "saving", but it has the same problem as before. I think the problem is I haven't do it correctly with "You need to clean your build dir first." @engineer1109

are u fix it? same problem ... followint

**Comment by niu-yq** [comment] 2023-04-30 06:29
> 
same problem...following
