### ISSUE TITLE
Attribute Error with pickle when running  train_shapes.ipynb

### ISSUE THREAD

**Issue by billybee** [matterport/Mask_RCNN#62] opened 2017-11-13 22:42 UTC
![attribute error](https://user-images.githubusercontent.com/33641096/32753197-3a786516-c889-11e7-894f-3a2da8ff2ecd.JPG)

**Comment by waleedka** [comment] 2017-11-13 22:52
Duplicate of #13

**Closed by waleedka** 2017-11-13 22:52 UTC
