### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by jinyu121** [matterport/Mask_RCNN#47] opened 2017-11-11 11:14 UTC
Hi~ I am training Mask RCNN on my dataset. During training, an error occured:

```
63/150 [===========>..................] - ETA: 1:05 - loss: 5.5540 - rpn_class_loss: 0.1711 - rpn_bbox_loss: 1.3187 - mrcnn_class_loss: 1.6656 - mrcnn_bbox_loss: 0.8899 - mrcnn_mask_loss: 0.6008
ERROR:root:Error processing image {'source': 'suncg', 'path': '/path/to/mlt/8a33bca7ed13c8d2698303625feba21a/000005.png', 'obj_mask_path': '/path/to/node/8a33bca7ed13c8d2698303625feba21a/000005.png', 'cls_mask_path': '/path/to/category/8a33bca7ed13c8d2698303625feba21a/000005.png', 'id': 8067}
Traceback (most recent call last):
  File "/home/haoyu/Workspace/Mask_RCNN/model.py", line 1523, in data_generator
    load_image_gt(dataset, config, image_id, augment=augment, use_mini_mask=config.USE_MINI_MASK)
  File "/home/haoyu/Workspace/Mask_RCNN/model.py", line 1148, in load_image_gt
    mask = utils.minimize_mask(bbox, mask, config.MINI_MASK_SHAPE)
  File "/home/haoyu/Workspace/Mask_RCNN/utils.py", line 436, in minimize_mask
    m = scipy.misc.imresize(m.astype(float), mini_shape, interp='bilinear')
  File "/home/haoyu/venv/lib/python3.4/site-packages/scipy/misc/pilutil.py", line 480, in imresize
    im = toimage(arr, mode=mode)
  File "/home/haoyu/venv/lib/python3.4/site-packages/scipy/misc/pilutil.py", line 299, in toimage
    cmin=cmin, cmax=cmax)
  File "/home/haoyu/venv/lib/python3.4/site-packages/scipy/misc/pilutil.py", line 90, in bytescale
    cmin = data.min()
  File "/home/haoyu/venv/lib/python3.4/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

Anyone can tell me how to fix it?

**Comment by zamponotiropita** [comment] 2017-11-13 11:18
Same here

**Comment by jinyu121** [comment] 2017-11-13 11:34
One quick (but dirty) fix:
In `utils.py`

```
def minimize_mask(bbox, mask, mini_shape):
    """Resize masks to a smaller version to cut memory load.
    Mini-masks can then resized back to image scale using expand_masks()

    See inspect_data.ipynb notebook for more details.
    """
    mini_mask = np.zeros(mini_shape + (mask.shape[-1],), dtype=bool)
    for i in range(mask.shape[-1]):
        m = mask[:, :, i]
        y1, x1, y2, x2 = bbox[i][:4]
        m = m[y1:y2, x1:x2]
        if len(np.unique(m)) > 0:
            m = scipy.misc.imresize(m.astype(float), mini_shape, interp='bilinear')
        else:
            m = np.zeros(mini_shape)
            m[0] = 128
        mini_mask[:, :, i] = np.where(m >= 128, 1, 0)
    return mini_mask
```

**Comment by Walid-Ahmed** [comment] 2017-11-13 16:46
@jinyu121 
Can you please how did you prepare your own dataset on the coco JSON format?
I used the software labelme but it outputs an xml file per image
Thanks

**Comment by jinyu121** [comment] 2017-11-14 08:30
@Walid-Ahmed try this: https://github.com/cvhciKIT/sloth

**Comment by waleedka** [comment] 2017-11-14 08:36
This error happens when you have an empty mask (all zeros). The bounding box is calculated from the mask (the smallest box that encapsulates all the pixels in the mask). So if the mask is all zeros, the bounding box dimensions will be zero as well, and that causes this error. I just pushed an update to detect if a bounding box area is zero and throw a better error message. Pull the latest update to get it. 

This update doesn't fix the problem above. It only improves it by showing the right error message. That would hopefully help in tracking why the bounding box area is zero and find the root cause.

**Comment by zamponotiropita** [comment] 2017-11-14 16:39
@jinyu121 I noticed that I get this error only when shrinking down the original image size. Maybe small masks disappear completely like that.

**Comment by Heavy02011** [comment] 2018-01-14 14:13
My problem seems to be related https://github.com/matterport/Mask_RCNN/issues/194 
When I apply the quick fix the error vanishes but now complains about a divide by zero...

**Comment by waleedka** [comment] 2018-03-30 08:47
I believe this issue is probably fixed in the update I mentioned above back in November, and also I just pushed another update that handles a separate, but maybe related edge case that happens with masks that are all 1s. 

Closing this for now. If you still have a problem with it, please start a new issue.

**Closed by waleedka** 2018-03-30 08:47 UTC

**Comment by arav38** [comment] 2020-01-04 16:08
Hello folks

Im having the same error when I using heatmap.Please suggest solution

ValueError: zero-size array to reduction operation minimum which has no identity
